[package]
name = "eigen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
itertools = "0.13.0"
num = "0.4.3"
thiserror = "1.0.61"

[lints.clippy]
pedantic = "warn"
nursery = "warn"
